#!/usr/bin/env bash
# Verify or insert the DSL license header on source files.
#
#   ./scripts/license-headers.sh           # add header where missing
#   ./scripts/license-headers.sh --check   # CI mode; exit 1 if any file is missing it
#
# Extensions handled: .go .js .ts .svelte .css .sql .sh .tf .tftpl .hcl .yaml .yml
set -euo pipefail

MARKER='SPDX-License-Identifier: LicenseRef-DSL-1.0'
HEADER_BODY='SPDX-License-Identifier: LicenseRef-DSL-1.0
Deferred Source License (DSL)
Pacer, Copyright (c) 2026 YouSysAdmin'

SKIP=(
  './bin/*'
  './frontend/dist/*'
  './frontend/node_modules/*'
  './frontend/.svelte-kit/*'
  './docs/themes/*'
  './docs/public/*'
  './docs/resources/*'
  './ui-kit/*'
  './vendor/*'
  './.git/*'
)

usage() {
  cat <<EOF
Usage: ${0##*/} [--check]

Default: inserts the DSL header at the top of any source file that doesn't
already contain '${MARKER}' in its first 10 lines.

--check: scans only; exits non-zero if any file lacks the marker.

Files containing 'Code generated by' in the first 5 lines are skipped.
EOF
}

mode=fix
case "${1:-}" in
  --check)   mode=check ;;
  -h|--help) usage; exit 0 ;;
  '')        ;;
  *)         usage; exit 2 ;;
esac

header_for() {
  case "$1" in
    *.svelte)                              printf '<!--\n%s\n-->\n\n' "$(printf '%s\n' "$HEADER_BODY" | sed 's|^|  |')" ;;
    *.css)                                 printf '/*\n%s\n */\n\n'   "$(printf '%s\n' "$HEADER_BODY" | sed 's|^| * |')" ;;
    *.sql)                                 printf '%s\n\n' "$(printf '%s\n' "$HEADER_BODY" | sed 's|^|-- |')" ;;
    *.sh|*.tf|*.tftpl|*.hcl|*.yaml|*.yml)  printf '%s\n\n' "$(printf '%s\n' "$HEADER_BODY" | sed 's|^|# |')"  ;;
    *)                                     printf '%s\n\n' "$(printf '%s\n' "$HEADER_BODY" | sed 's|^|// |')" ;;
  esac
}

prune=()
for s in "${SKIP[@]}"; do
  prune+=( -path "$s" -o )
done
unset 'prune[${#prune[@]}-1]'

missing=0
processed=0
changed=0

while IFS= read -r -d '' f; do
  processed=$((processed + 1))
  if head -n 5  "$f" 2>/dev/null | grep -q  'Code generated by'; then continue; fi
  if head -n 10 "$f" 2>/dev/null | grep -qF "$MARKER";          then continue; fi

  if [[ $mode == check ]]; then
    echo "missing: $f" >&2
    missing=$((missing + 1))
    continue
  fi

  tmp=$(mktemp)
  first=$(head -n 1 "$f" 2>/dev/null || true)
  if [[ "$first" == \#!* ]]; then
    printf '%s\n' "$first" >"$tmp"
    header_for "$f" >>"$tmp"
    tail -n +2 "$f" >>"$tmp"
  else
    header_for "$f" >"$tmp"
    cat "$f" >>"$tmp"
  fi
  mv "$tmp" "$f"
  echo "added: $f"
  changed=$((changed + 1))
done < <(
  find . \( "${prune[@]}" \) -prune -o \
         \( -name '*.go' -o -name '*.js' -o -name '*.ts' \
            -o -name '*.svelte' -o -name '*.css' -o -name '*.sql' \
            -o -name '*.sh' -o -name '*.tf' -o -name '*.tftpl' \
            -o -name '*.hcl' -o -name '*.yaml' -o -name '*.yml' \) \
         -type f -print0
)

if [[ $mode == check ]]; then
  if (( missing > 0 )); then
    echo "$missing of $processed file(s) missing license header" >&2
    exit 1
  fi
  echo "all $processed file(s) ok"
else
  echo "$changed of $processed file(s) updated"
fi
